[[redirects]]
  from = "/"
  to = "https://pinniped.dev"
  status = 302
  force = true

[[redirects]]
  from = "/cli"
  to = "https://pinniped.dev/docs/howto/install-cli"
  status = 302
  force = true

[[redirects]]
  from = "/latest/*"
  to = "https://github.com/vmware/pinniped/releases/latest/download/:splat"
  status = 302
  force = true

[[redirects]]
  from = "/*"
  to = "https://github.com/vmware/pinniped/releases/download/:splat"
  status = 302
  force = true
